DELETE http://localhost:3001/api/users/11

###

GET http://localhost:3001/api/users

###

GET http://localhost:3001/api/users/5

###

PATCH http://localhost:3001/api/users/5
Content-Type: application/json

{
    "name": "",
    "email":"",
    "password":"joeljoeljoel"
}